name: school_management
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  another_flushbar: ^1.12.29
  dartz: ^0.10.1
  dio: ^4.0.6
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.2
  google_fonts: ^4.0.1
  hive_flutter: ^1.1.0
  hooked_bloc: ^1.3.0
  injectable: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  hive_generator: ^2.0.0
  flutter_gen_runner: ^5.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
